GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNjExNjkwNTc5LCJleHAiOjE2MTE2OTA2MDl9.AW-l8X3_R9J6cIYwjzgWgZ_yv1uUkVhos3nl4zQ-jZs

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNjExNjkwNDk2fQ.849v16QbSIeZtxr3dIepPnHgyPkSKjUXHeunBAcigRI"
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNjExNjkwNDk2fQ.849v16QbSIeZtxr3dIepPnHgyPkSKjUXHeunBAcigRI"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "jim"
}